AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  DynamoDB Tables

Parameters:
  ResourceGroupName:
    Type: String
    Description: Name of the ResourceGroup for resources in this template

Resources:
  ResourceGroup:
    Type: "AWS::ResourceGroups::Group"
    Properties:
      Name: !Sub "${ResourceGroupName}"
  ConnectionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: connectionId
        AttributeType: S
      KeySchema:
      - AttributeName: connectionId
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 6
        WriteCapacityUnits: 6
      SSESpecification:
        SSEEnabled: True
  ActiveGamesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: gameId
        AttributeType: S
      - AttributeName: playerName
        AttributeType: S
      KeySchema:
      - AttributeName: gameId
        KeyType: HASH
      - AttributeName: playerName
        KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: HostGames
          KeySchema:
          - AttributeName: playerName
            KeyType: HASH
          - AttributeName: gameId
            KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: True
  GamesDetailTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: gameId
        AttributeType: S
      - AttributeName: questionNumber
        AttributeType: N
      KeySchema:
      - AttributeName: gameId
        KeyType: HASH
      - AttributeName: questionNumber
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: True
  HighScoreTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: gameId
        AttributeType: S
      - AttributeName: playerName
        AttributeType: S
      - AttributeName: score
        AttributeType: N
      KeySchema:
      - AttributeName: gameId
        KeyType: HASH
      - AttributeName: playerName
        KeyType: RANGE
      GlobalSecondaryIndexes:
      - IndexName: GameScore
        KeySchema:
        - AttributeName: gameId
          KeyType: HASH
        - AttributeName: score
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: True
  GamePlayersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: gameId
        AttributeType: S
      - AttributeName: connectionId
        AttributeType: S
      - AttributeName: role
        AttributeType: S
      KeySchema:
      - AttributeName: gameId
        KeyType: HASH
      - AttributeName: connectionId
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: True
      LocalSecondaryIndexes:
      - IndexName: GameRole
        KeySchema:
        - AttributeName: gameId
          KeyType: HASH
        - AttributeName: role
          KeyType: RANGE
        Projection:
          ProjectionType: ALL
  PlayerTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: playerName
        AttributeType: S
      KeySchema:
      - AttributeName: playerName
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 6
        WriteCapacityUnits: 6
      SSESpecification:
        SSEEnabled: True
  PlayerWalletTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: playerName
        AttributeType: S
      KeySchema:
      - AttributeName: playerName
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 6
        WriteCapacityUnits: 6
      SSESpecification:
        SSEEnabled: True
  PlayerProgressTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: playerName
        AttributeType: S
      - AttributeName: experience
        AttributeType: N
      KeySchema:
      - AttributeName: playerName
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 6
        WriteCapacityUnits: 6
      SSESpecification:
        SSEEnabled: True
      GlobalSecondaryIndexes:
        - IndexName: XPIndex
          KeySchema:
          - AttributeName: experience
            KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
  PlayerInventoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: playerName
        AttributeType: S
      - AttributeName: gameId
        AttributeType: S
      KeySchema:
      - AttributeName: playerName
        KeyType: HASH
      - AttributeName: gameId
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 6
        WriteCapacityUnits: 6
      SSESpecification:
        SSEEnabled: True
  MarketplaceTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: playerName
        AttributeType: S
      - AttributeName: gameId
        AttributeType: S
      KeySchema:
      - AttributeName: gameId
        KeyType: HASH
      - AttributeName: playerName
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 6
        WriteCapacityUnits: 6
      SSESpecification:
        SSEEnabled: True

Outputs:
  ConnectionsTable:
    Description: DynamoDB Table to manage WebSocket Connections
    Value: !Ref ConnectionsTable
    Export:
      Name: !Sub "${AWS::StackName}-ConnectionsTable"
  ActiveGamesTable:
    Description: DynamoDB Table to manage Active / Running Games
    Value: !Ref ActiveGamesTable
    Export:
      Name: !Sub "${AWS::StackName}-ActiveGamesTable"
  GamesDetailTable:
    Description: DynamoDB Table to manage Game Details
    Value: !Ref GamesDetailTable
    Export:
      Name: !Sub "${AWS::StackName}-GamesDetailTable"
  HighScoreTable:
    Description: DynamoDB Table to manage High Scores
    Value: !Ref HighScoreTable
    Export:
      Name: !Sub "${AWS::StackName}-HighScoreTable"
  GamePlayersTable:
    Description: DynamoDB Table to manage Players in a Live Game
    Value: !Ref GamePlayersTable
    Export:
      Name: !Sub "${AWS::StackName}-GamePlayersTable"
  PlayerTable:
    Description: DynamoDB Table to manage Player Profiles
    Value: !Ref PlayerTable
    Export:
      Name: !Sub "${AWS::StackName}-PlayerTable"
  PlayerProgressTable:
    Description: DynamoDB Table to manage Player Progression
    Value: !Ref PlayerProgressTable
    Export:
      Name: !Sub "${AWS::StackName}-PlayerProgressTable"
  PlayerWalletTable:
    Description: DynamoDB Table to manage Player Wallet
    Value: !Ref PlayerWalletTable
    Export:
      Name: !Sub "${AWS::StackName}-PlayerWalletTable"
  PlayerInventoryTable:
    Description: DynamoDB Table to manage Player Inventory
    Value: !Ref PlayerInventoryTable
    Export:
      Name: !Sub "${AWS::StackName}-PlayerInventoryTable"
  MarketplaceTable:
    Description: DynamoDB Table to manage Marketplace
    Value: !Ref MarketplaceTable
    Export:
      Name: !Sub "${AWS::StackName}-MarketplaceTable"






