version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sts"
s3_prefix = "sts"
capabilities = "CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = ""
image_repositories = []
