AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Backend for Websockets (including functions)

Globals:
  Function:
    Runtime: nodejs12.x
    Handler: app.handler
    MemorySize: 512 
    Timeout: 10
    Tracing: Active
    Environment:
      Variables:
        AWS_EMF_NAMESPACE: !Sub "${EMFNamespace}"
    Layers:
      - !Sub "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:14"

Parameters:
  GamePlayersTable:
    Type: String
    Description: Table name for players in a live game
  PlayerInventoryTable:
    Type: String
    Description: Player inventory table
  PlayerWalletTable:
    Type: String
    Description: Player wallet table
  HighScoreTable:
    Type: String
    Description: Table for game high scores
  GamesDetailTable:
    Type: String
    Description: Table for Game Questions
  PlayerProgressTopicName:
    Type: String
    Description: Topic Name for sending player progress
  PlayerProgressTopicArn:
    Type: String
    Description: Topic Arn for sending player progress
  UserPoolID:
    Type: String
    Description: Cognito User Pool ID for users
  LogRetentionDays:
    Type: Number
    Description: CloudWatch Log Retention Days
  ResourceGroupName:
    Type: String
    Description: Name of the ResourceGroup for resources in this template
  EMFNamespace:
    Type: String
    Description: Name of the EMF Namespace
  QuizSourceStreamName:
    Type: String
    Description: Stream for results
  ChatTopicName:
    Type: String
    Description: Name for the SNS Chat Topic
  ChatTopicArn:
    Type: String
    Description: Arn for the SNS Chat Topic
  EventBusName:
    Type: String
    Description: Name of the EventBus

Resources:
  ResourceGroup:
    Type: "AWS::ResourceGroups::Group"
    Properties:
      Name: !Sub "${ResourceGroupName}"
  SendChatLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub 'chatlayer--${AWS::StackName}'
      Description: SendChat back via WebSockets
      ContentUri: dependencies/sendchatlayer/nodejs/sendchatlayer.zip
      CompatibleRuntimes:
        - nodejs12.x
      LicenseInfo: 'MIT'
      RetentionPolicy: Retain
  WebSocket:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: WebSocket
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: "$request.body.message"

  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocket
      RouteKey: $connect
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref WSAuthorizer
      OperationName: ConnectRoute
  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocket
      RouteKey: $disconnect
      AuthorizationType: NONE
      OperationName: DisconnectRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref DisconnectInteg
  DisconnectInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocket
      Description: Disconnect Integration
      IntegrationType: AWS_PROXY
      TimeoutInMillis: 5000
      IntegrationUri: 
        Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OnDisconnectFunction.Arn}:Live/invocations
  LiveGameAdminRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocket
      RouteKey: liveadmin
      AuthorizationType: NONE
      OperationName: LiveAdminRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref LiveGameAdminInteg
  LiveGameAdminInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocket
      Description: LiveGameAdmin Integration
      IntegrationType: AWS_PROXY
      TimeoutInMillis: 5000
      IntegrationUri: 
        Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LiveGameAdminFunction.Arn}:Live/invocations
  LiveGamePlayerRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocket
      RouteKey: liveplayer
      AuthorizationType: NONE
      OperationName: LivePlayerRoute
      Target: !Sub 'integrations/${LiveGamePlayerInteg}'
  LiveGamePlayerInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocket
      Description: LiveGamePlayer Integration
      TimeoutInMillis: 5000
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LiveGamePlayerFunction.Arn}:Live/invocations
  WebSocketDeployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
    - ConnectRoute
    - DisconnectRoute
    - LiveGamePlayerRoute
    - LiveGameAdminRoute
    - WSAuthorizer
    Properties:
      ApiId: !Ref WebSocket
  WebSocketStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: Prod
      Description: Prod Stage
      DeploymentId: !Ref WebSocketDeployment
      ApiId: !Ref WebSocket
      Tags:
        Dashboard: WebSocket

  OnDisconnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Functions/WebSockets/ondisconnect/
      Environment:
        Variables:
          GAME_PLAYERS_TABLE_NAME: !Sub "${GamePlayersTable}"
          REGION: !Sub ${AWS::Region}
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Sub "${GamePlayersTable}"
        - CloudWatchLambdaInsightsExecutionRolePolicy
      Tags:
        Dashboard: WebSocket
  OnDisconnectFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      RetentionInDays: 14
      LogGroupName: !Join ["", ["/aws/lambda/", !Ref OnDisconnectFunction]]
  OnDisconnectPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - WebSocket
      - OnDisconnectAlias
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Join [":", [!Ref OnDisconnectFunction, "Live"]]
      Principal: apigateway.amazonaws.com
  OnDisconnectVersion:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref OnDisconnectFunction
  OnDisconnectAlias:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref OnDisconnectFunction
      FunctionVersion: !GetAtt OnDisconnectVersion.Version
      Name: Live
      
  AuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Functions/WebSockets/auth/
      Environment:
        Variables:
          REGION: !Sub "${AWS::Region}"
          POOL_ID:  !Sub "${UserPoolID}"
          API_ID: !Ref WebSocket
          STAGE: Prod
      Tags:
        Dashboard: WebSocket
  AuthorizerFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      RetentionInDays: !Sub "${LogRetentionDays}"
      LogGroupName: !Join ["", ["/aws/lambda/", !Ref AuthorizerFunction]]
  AuthorizerVersion:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref AuthorizerFunction
  AuthorizerAlias:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref AuthorizerFunction
      FunctionVersion: !GetAtt AuthorizerVersion.Version
      Name: Live
  
  AuthorizerPermissions:
    Type: AWS::Lambda::Permission
    DependsOn:
      - WebSocket
      - AuthorizerAlias
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Join [":", [!Ref AuthorizerFunction, "Live"]]
      Principal: apigateway.amazonaws.com
  WSAuthorizer:
    Type: AWS::ApiGatewayV2::Authorizer
    Properties: 
      AuthorizerType: REQUEST
      ApiId: !Ref WebSocket
      IdentitySource: 
        - route.request.querystring.access_token
      AuthorizerUri: !Join
        - ''
        - - "arn:aws:apigateway:"
          - !Sub ${AWS::Region}
          - ":lambda:path/2015-03-31/functions/"
          - !GetAtt AuthorizerFunction.Arn
          - ":Live"
          - "/invocations"
      Name: WSAuth
  LiveGamePlayerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Functions/WebSockets/livegameplayer/
      MemorySize: 1536
      Layers: 
        - !Ref SendChatLayer
      Environment:
        Variables:
          PLAYER_INVENTORY_TABLE_NAME: !Sub "${PlayerInventoryTable}"
          PLAYERS_TABLE_NAME: !Sub "${GamePlayersTable}"
          REGION: !Sub "${AWS::Region}"
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Sub "${GamePlayersTable}"
        - DynamoDBReadPolicy:
            TableName: !Sub "${PlayerInventoryTable}"
        - !Ref WebSocketManageConnectionsPolicy
        - CloudWatchLambdaInsightsExecutionRolePolicy
      Tags:
        Dashboard: WebSocket
  LiveGamePlayerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      RetentionInDays: !Sub "${LogRetentionDays}"
      LogGroupName: !Join ["", ["/aws/lambda/", !Ref LiveGamePlayerFunction]]
  LiveGamePlayerVersion:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref LiveGamePlayerFunction
  LiveGamePlayerAlias:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref LiveGamePlayerFunction
      FunctionVersion: !GetAtt LiveGamePlayerVersion.Version
      Name: Live
  LiveGamePlayerPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - WebSocket
      - LiveGamePlayerAlias
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Join [":", [!Ref LiveGamePlayerFunction, "Live"]]
      Principal: apigateway.amazonaws.com
  LiveGameAdminFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Functions/WebSockets/livegameadmin/
      MemorySize: 1536
      Layers: 
        - !Ref SendChatLayer
      Environment:
        Variables:
          SCORES_TABLE_NAME: !Sub "${HighScoreTable}"
          GAMES_DETAIL_TABLE_NAME: !Sub "${GamesDetailTable}"
          PLAYERS_TABLE_NAME: !Sub "${GamePlayersTable}"
          PLAYER_PROGRESS_TOPIC: !Sub "${PlayerProgressTopicArn}"
          PLAYER_INVENTORY_TABLE_NAME: !Sub "${PlayerInventoryTable}"
          RESPONSE_STREAM: !Sub "${QuizSourceStreamName}"
          CHAT_TOPIC_ARN: !Sub "${ChatTopicArn}"
          EVENT_BUS_NAME: !Sub "${EventBusName}"
          REGION: !Sub "${AWS::Region}"
      Policies:
        - KinesisCrudPolicy:
            StreamName: !Sub "${QuizSourceStreamName}"
        - SNSPublishMessagePolicy:
            TopicName: !Sub "${PlayerProgressTopicName}"
        - DynamoDBCrudPolicy:
            TableName: !Sub "${HighScoreTable}"
        - DynamoDBCrudPolicy:
            TableName: !Sub "${GamePlayersTable}"
        - DynamoDBReadPolicy:
            TableName: !Sub "${GamesDetailTable}"
        - DynamoDBCrudPolicy:
            TableName: !Sub "${PlayerInventoryTable}"
        - SNSPublishMessagePolicy:
            TopicName: !Sub "${ChatTopicName}"
        - EventBridgePutEventsPolicy:
            EventBusName: !Sub "${EventBusName}"
        - CloudWatchLambdaInsightsExecutionRolePolicy
        - !Ref WebSocketManageConnectionsPolicy
      Tags:
        Dashboard: WebSocket
  LiveGameAdminFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      RetentionInDays: !Sub "${LogRetentionDays}"
      LogGroupName: !Join ["", ["/aws/lambda/", !Ref LiveGameAdminFunction]]
  LiveGameAdminVersion:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref LiveGameAdminFunction
  LiveGameAdminAlias:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref LiveGameAdminFunction
      FunctionVersion: !GetAtt LiveGameAdminVersion.Version
      Name: Live
  LiveGameAdminPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - WebSocket
      - LiveGameAdminAlias
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Join [":", [!Ref LiveGameAdminFunction, "Live"]]
      Principal: apigateway.amazonaws.com

  GameDataDeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      AutoPublishAlias: Live
      CodeUri: Functions/WebSockets/gameplayer_delete/
      MemorySize: 1536
      Environment:
        Variables:
          PLAYERS_TABLE_NAME: !Sub "${GamePlayersTable}"
          REGION: !Sub "${AWS::Region}"
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Sub "${GamePlayersTable}"
      Events:
        EBEvent:
          Type: EventBridgeRule
          Properties:
            Pattern:
              detail-type:
                - "Websockets.game_end"
            RetryPolicy:
              MaximumRetryAttempts: 5
              MaximumEventAgeInSeconds: 60
            EventBusName: !Sub "${EventBusName}"
      Tags:
        Dashboard: WebSocket

  WebSocketManageConnectionsPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Join ["", [!Ref "AWS::StackName", "WebSocketManageConnectionsPolicy" ] ] 
      PolicyDocument:
        Version: "2012-10-17"
        Statement: 
          - Effect: Allow
            Action:
            - 'execute-api:ManageConnections'
            Resource:
            - !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocket}/*'
  
Outputs:
  WebSocketURI:
    Description: "The WSS Protocol URI to connect to"
    Value: !Join [ '', [ 'wss://', !Ref WebSocket, '.execute-api.',!Ref 'AWS::Region','.amazonaws.com/',!Ref 'WebSocketStage'] ]
    
  WebSocketAPIGWId:
    Description: "ID of the API Gateway used for websockets"
    Value: !Ref WebSocket
    Export:
      Name: !Sub "${AWS::StackName}-APIGWID"

  Stage:
    Description: "Stage for WS API"
    Value: !Ref WebSocketStage
